unbind r
bind r source-file ~/.tmux.conf

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -g prefix C-s

set -g mouse on

set-window-option -g mode-keys vi

bind -n C-Left  resize-pane -L 5
bind -n C-Right resize-pane -R 5
bind -n C-Up    resize-pane -U 5
bind -n C-Down  resize-pane -D 5

bind '"' split-window -v -p 20
bind '%' split-window -h -p 20

set-option -g status-position top


# # Monokai Classic-ish palette
set -g @thm_bg         "#272822"
set -g @thm_fg         "#F8F8F2"
set -g @thm_surface_0  "#3E3D32"
set -g @thm_surface_1  "#49483E"
set -g @thm_overlay_0  "#75715E"

set -g @thm_red        "#F92672"
set -g @thm_green      "#A6E22E"
set -g @thm_yellow     "#E6DB74"
set -g @thm_blue       "#66D9EF"
set -g @thm_mauve      "#AE81FF"
set -g @thm_peach      "#FD971F"
set -g @thm_lavender   "#66D9EF"


# set -g @catppuccin_flavor "mocha"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_text " #{b:pane_current_command}"
set -g @catppuccin_window_current_text " #{b:pane_current_path}: #{b:pane_current_command}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v2.3.0'
# set -g @plugin 'christoomey/vim-tmux-navigator'

# # Monokai Classic colors
set -g @catppuccin_status_background "#272822"

set -g @catppuccin_window_number_color "#75715E"
set -g @catppuccin_window_current_number_color "#66D9EF"

set -g @catppuccin_pane_border_style "fg=#75715E"
set -g @catppuccin_pane_active_border_style "fg=#A6E22E"


set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g status-style bg=default


